In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('ipf_reg_2000.csv')
df.head()

,Name,Sex,Event,Equipment,Division,WeightClassKg,Squat1Kg,Bench1Kg,Deadlift1Kg,ProjectedTotal
0,Taylor Atwood,M,SBD,Raw,MR-O,74,255.0,180.0,277.5,712.5
1,Chase Gaddy,M,SBD,Single-ply,M-V,75,217.5,135.0,210.0,562.5
2,Antti Liimatainen,M,SBD,Single-ply,Over 40,83,180.0,130.0,225.0,535.0
3,Keith Bowen,M,SBD,Single-ply,M-O,90,272.5,160.0,280.0,712.5
4,Sophia Ellis,F,SBD,Raw,FR-Jr,84,130.0,92.5,180.0,402.5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            2000 non-null   object
 1   Sex             2000 non-null   object
 2   Event           2000 non-null   object
 3   Equipment       2000 non-null   object
 4   Division        2000 non-null   object
 5   WeightClassKg   2000 non-null   object
 6   Squat1Kg        2000 non-null   float64
 7   Bench1Kg        2000 non-null   float64
 8   Deadlift1Kg     2000 non-null   float64
 9   ProjectedTotal  2000 non-null   float64
dtypes: float64(4), object(6)
memory usage: 156.4+ KB

In [4]:
df.describe()

          Squat1Kg     Bench1Kg  Deadlift1Kg  ProjectedTotal
count  2000.000000  2000.000000  2000.000000     2000.000000
mean    165.577395   106.582930   183.835470      455.995795
std      59.813516    43.866389    56.110399      154.102727
min      25.000000    25.000000    75.000000      125.000000
25%     120.000000    70.000000   139.375000      330.000000
50%     162.500000   105.000000   185.000000      452.500000
75%     205.000000   135.000000   225.000000      560.000000
max     410.000000   280.000000   350.000000     1020.000000

In [5]:
print(df['Event'].value_counts())
df_sbd = df[df['Event'] == 'SBD']
df_sbd['Event'].value_counts()

Event
SBD    2000
Name: count, dtype: int64

Event
SBD    2000
Name: count, dtype: int64