In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('ipf2000.csv')
df.head()

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
0,Stanislav Fedoseev,M,SBD,Raw,17.5,18-19,14-18,Sub-Juniors,46.85,48,...,NaN,NaN,FPR,IPF,2015-11-21,Russia,IRK,Irkutsk,Irkutsk Oblast Juniors & Sub-Juniors Powerlift...,Yes
1,Anastasiya Sled,F,SBD,Raw,29.0,24-34,24-39,Open,56.88,57,...,Russia,NaN,FPR,IPF,2014-12-03,Russia,MOW,Moscow,Central District & Moscow Powerlifting Champio...,Yes
2,Ilse Cretskens,F,SBD,Raw,44.0,40-44,40-49,Masters 1,121.30,84+,...,Belgium,NaN,KBGV,IPF,2025-04-26,Belgium,NaN,Izegem,Belgisch Kampioenschap - Championnats de Belgi...,Yes
3,Louis Zamora,M,SBD,Single-ply,NaN,NaN,NaN,Class 2,75.00,75,...,NaN,NaN,USPF,IPF,1990-02-03,USA,TX,San Antonio,Alamo Classic,Yes
4,Zach Dichard,M,SBD,Raw,22.5,20-23,19-23,MR-Jr,82.60,83,...,USA,VT,USAPL,IPF,2019-04-13,USA,NY,NaN,Spring Break Throwdown II,Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 42 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              2000 non-null   object
 1   Sex               2000 non-null   object
 2   Event             2000 non-null   object
 3   Equipment         2000 non-null   object
 4   Age               1478 non-null   float64
 5   AgeClass          1556 non-null   object
 6   BirthYearClass    1581 non-null   object
 7   Division          1998 non-null   object
 8   BodyweightKg      1976 non-null   float64
 9   WeightClassKg     1972 non-null   object
 10  Squat1Kg          813 non-null    float64
 11  Squat2Kg          806 non-null    float64
 12  Squat3Kg          782 non-null    float64
 13  Squat4Kg          0 non-null      float64
 14  Best3SquatKg      1461 non-null   float64
 15  Bench1Kg          1116 non-null   float64
 16  Bench2Kg          1109 non-null   float64
 17  Bench3Kg          1082 non-null   float64
 18  Bench4Kg          1 non-null      float64
 19  Best3BenchKg      1884 non-null   float64
 20  Deadlift1Kg       833 non-null    float64
 21  Deadlift2Kg       826 non-null    float64
 22  Deadlift3Kg       808 non-null    float64
 23  Deadlift4Kg       0 non-null      float64
 24  Best3DeadliftKg   1493 non-null   float64
 25  TotalKg           1918 non-null   float64
 26  Place             2000 non-null   object
 27  Dots              1894 non-null   float64
 28  Wilks             1894 non-null   float64
 29  Glossbrenner      1894 non-null   float64
 30  Goodlift          1833 non-null   float64
 31  Tested            1782 non-null   object
 32  Country           1118 non-null   object
 33  State             330 non-null    object
 34  Federation        2000 non-null   object
 35  ParentFederation  2000 non-null   object
 36  Date              2000 non-null   object
 37  MeetCountry       2000 non-null   object
 38  MeetState         1077 non-null   object
 39  MeetTown          1701 non-null   object
 40  MeetName          2000 non-null   object
 41  Sanctioned        2000 non-null   object
dtypes: float64(22), object(20)
memory usage: 656.4+ KB

In [5]:
df.describe()

,Age,BodyweightKg,Squat1Kg,Squat2Kg,Squat3Kg,Squat4Kg,Best3SquatKg,Bench1Kg,Bench2Kg,Bench3Kg,...,Deadlift1Kg,Deadlift2Kg,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Dots,Wilks,Glossbrenner,Goodlift
count,1478.000000,1976.000000,813.000000,806.000000,782.000000,0.0,1461.000000,1116.000000,1109.00000,1082.000000,...,833.000000,826.000000,808.000000,0.0,1493.000000,1918.000000,1894.000000,1894.000000,1894.000000,1833.000000
mean,29.358254,82.763861,122.808057,113.210161,59.277724,NaN,182.613682,84.821281,55.04716,-10.610582,...,161.934442,145.600642,26.315470,NaN,200.439786,410.280334,300.537835,299.115317,281.864593,66.756296
std,12.905221,21.228281,123.699486,144.840007,180.328892,NaN,67.571777,87.384172,115.59843,131.462040,...,99.079901,139.958783,208.208062,NaN,60.143157,214.920356,133.913170,133.179228,126.475952,15.233701
min,6.500000,24.950000,-360.000000,-360.000000,-446.000000,NaN,-265.000000,-340.000000,-310.00000,-363.000000,...,-310.000000,-337.500000,-375.000000,NaN,-210.000000,2.500000,1.510000,1.500000,1.430000,1.120000
25%,19.500000,67.500000,100.000000,90.000000,-129.375000,NaN,132.500000,60.000000,-40.00000,-122.500000,...,130.000000,127.500000,-190.625000,NaN,152.500000,222.500000,179.912500,179.860000,167.330000,56.870000
50%,25.000000,81.665000,150.000000,155.000000,132.500000,NaN,180.000000,100.000000,90.00000,-57.500000,...,175.000000,181.250000,130.000000,NaN,204.120000,418.440000,334.360000,332.460000,312.445000,67.420000
75%,36.500000,95.750000,195.000000,202.500000,196.125000,NaN,225.000000,135.000000,135.00000,112.500000,...,220.000000,230.000000,210.000000,NaN,245.000000,577.140000,398.045000,395.197500,374.772500,77.530000
max,84.000000,177.800000,400.000000,420.000000,435.000000,NaN,435.000000,300.000000,342.50000,280.000000,...,350.000000,365.000000,377.500000,NaN,377.500000,1092.500000,628.830000,617.580000,590.430000,113.630000

In [4]:
print(df['Event'].value_counts())
df_sbd = df[df['Event'] == 'SBD']
df_sbd['Event'].value_counts()

Event
SBD    1487
B       450
D        45
BD       13
S         4
SD        1
Name: count, dtype: int64

Event
SBD    1487
Name: count, dtype: int64