In [3]:
import pandas as pd

df = pd.read_csv('ipf.csv')

df.info()

C:\Users\jackm\AppData\Local\Temp\ipykernel_22284\3744460308.py:3: DtypeWarning: Columns (33,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ipf.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372159 entries, 0 to 1372158
Data columns (total 42 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Name              1372159 non-null  object
 1   Sex               1372159 non-null  object
 2   Event             1372159 non-null  object
 3   Equipment         1372159 non-null  object
 4   Age               1011712 non-null  float64
 5   AgeClass          1057140 non-null  object
 6   BirthYearClass    1074518 non-null  object
 7   Division          1370950 non-null  object
 8   BodyweightKg      1357103 non-null  float64
 9   WeightClassKg     1356035 non-null  object
 10  Squat1Kg          580439 non-null   float64
 11  Squat2Kg          575078 non-null   float64
 12  Squat3Kg          562169 non-null   float64
 13  Squat4Kg          328 non-null      float64
 14  Best3SquatKg      992848 non-null   float64
 15  Bench1Kg          808587 non-null   float64
 16  Bench2Kg          801605 non-null   float64
 17  Bench3Kg          782633 non-null   float64
 18  Bench4Kg          1261 non-null     float64
 19  Best3BenchKg      1287801 non-null  float64
 20  Deadlift1Kg       593099 non-null   float64
 21  Deadlift2Kg       584551 non-null   float64
 22  Deadlift3Kg       566448 non-null   float64
 23  Deadlift4Kg       475 non-null      float64
 24  Best3DeadliftKg   1009019 non-null  float64
 25  TotalKg           1298803 non-null  float64
 26  Place             1372159 non-null  object
 27  Dots              1285497 non-null  float64
 28  Wilks             1285497 non-null  float64
 29  Glossbrenner      1285497 non-null  float64
 30  Goodlift          1251665 non-null  float64
 31  Tested            1228468 non-null  object
 32  Country           798369 non-null   object
 33  State             243148 non-null   object
 34  Federation        1372159 non-null  object
 35  ParentFederation  1372159 non-null  object
 36  Date              1372159 non-null  object
 37  MeetCountry       1372159 non-null  object
 38  MeetState         745941 non-null   object
 39  MeetTown          1150296 non-null  object
 40  MeetName          1372159 non-null  object
 41  Sanctioned        1372159 non-null  object
dtypes: float64(22), object(20)
memory usage: 439.7+ MB

In [4]:
df.head()

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName,Sanctioned
0,Amy Clair,F,SBD,Raw,36.0,35-39,24-39,Open,75.54,76,...,Australia,NaN,APLA,IPF,2024-10-20,Australia,SA,NaN,AUPC Powerlifting Open,Yes
1,Ruby Olthoff,F,SBD,Raw,17.0,16-17,14-18,Sub-Junior,69.44,76,...,Australia,NaN,APLA,IPF,2024-10-20,Australia,SA,NaN,AUPC Powerlifting Open,Yes
2,Wai Hang Wong,M,SBD,Raw,21.0,20-23,19-23,Junior,70.64,74,...,Australia,NaN,APLA,IPF,2024-10-20,Australia,SA,NaN,AUPC Powerlifting Open,Yes
3,Jonathan Chan #2,M,SBD,Raw,23.0,20-23,19-23,Junior,81.34,83,...,Australia,NaN,APLA,IPF,2024-10-20,Australia,SA,NaN,AUPC Powerlifting Open,Yes
4,Sung Hoon Ok,M,SBD,Raw,22.0,20-23,19-23,Junior,92.42,93,...,Australia,NaN,APLA,IPF,2024-10-20,Australia,SA,NaN,AUPC Powerlifting Open,Yes

In [6]:
df_registration = df[['Name', 'Sex', 'Event', 'Equipment', 'Division', 'WeightClassKg', 'Squat1Kg', 'Bench1Kg', 'Deadlift1Kg']]
df_registration['ProjectedTotal'] = df_registration[['Squat1Kg', 'Bench1Kg', 'Deadlift1Kg']].sum(axis=1)
df_registration.head()

C:\Users\jackm\AppData\Local\Temp\ipykernel_22284\2986297730.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_registration['ProjectedTotal'] = df_registration[['Squat1Kg', 'Bench1Kg', 'Deadlift1Kg']].sum(axis=1)

,Name,Sex,Event,Equipment,Division,WeightClassKg,Squat1Kg,Bench1Kg,Deadlift1Kg,ProjectedTotal
0,Amy Clair,F,SBD,Raw,Open,76,132.5,82.5,140.0,355.0
1,Ruby Olthoff,F,SBD,Raw,Sub-Junior,76,135.0,70.0,160.0,365.0
2,Wai Hang Wong,M,SBD,Raw,Junior,74,185.0,105.0,200.0,490.0
3,Jonathan Chan #2,M,SBD,Raw,Junior,83,195.0,130.0,215.0,540.0
4,Sung Hoon Ok,M,SBD,Raw,Junior,93,237.5,147.5,257.5,642.5

In [8]:
df_registration.size

13721590

In [9]:
df_registration = df_registration[df_registration['Event'] == 'SBD']

In [16]:
df_registration = df_registration.dropna()
df_registration.size

5651330

In [13]:
df_registration.head()

,Name,Sex,Event,Equipment,Division,WeightClassKg,Squat1Kg,Bench1Kg,Deadlift1Kg,ProjectedTotal
0,Amy Clair,F,SBD,Raw,Open,76,132.5,82.5,140.0,355.0
1,Ruby Olthoff,F,SBD,Raw,Sub-Junior,76,135.0,70.0,160.0,365.0
2,Wai Hang Wong,M,SBD,Raw,Junior,74,185.0,105.0,200.0,490.0
3,Jonathan Chan #2,M,SBD,Raw,Junior,83,195.0,130.0,215.0,540.0
4,Sung Hoon Ok,M,SBD,Raw,Junior,93,237.5,147.5,257.5,642.5

In [14]:
df_test = df.dropna()
df_test.size

0

In [23]:
dfreg_sample = df_registration.sample(n=2000, random_state=42).reset_index().drop('index', axis=1)
dfreg_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            2000 non-null   object
 1   Sex             2000 non-null   object
 2   Event           2000 non-null   object
 3   Equipment       2000 non-null   object
 4   Division        2000 non-null   object
 5   WeightClassKg   2000 non-null   object
 6   Squat1Kg        2000 non-null   float64
 7   Bench1Kg        2000 non-null   float64
 8   Deadlift1Kg     2000 non-null   float64
 9   ProjectedTotal  2000 non-null   float64
dtypes: float64(4), object(6)
memory usage: 156.4+ KB

In [24]:
dfreg_sample.to_csv('ipf_reg_2000.csv', index=False)